Much better syntax highlighting

diff --git a/vim/install b/vim/install
--- a/vim/install
+++ b/vim/install
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+CWD=$(pwd)
+
 echo ""
 echo "Installing Vim environment"
 
@@ -25,23 +27,43 @@ echo ""
 
 # Generic function for installing plugins using Pathogen
 install_plugin() {
-echo "    Installing ${1}"
-echo "        Cloning..."
+	echo "    Installing ${1}"
+	echo "        Cloning..."
 
-{
-	cd ~/.vim/bundle/
-	git clone --quiet --recursive ${2}
+	{
+		cd ~/.vim/bundle/
+		git clone --quiet --recursive ${2}
 
-	echo "    Installed ${1}"
-} || {
-	echo "    Couldn't install ${1}"
+		echo "    Installed ${1}"
+	} || {
+		echo "    Couldn't install ${1}"
+	}
+
+	echo ""
 }
 
-echo ""
+# Generic function for installing provided files
+install_files() {
+	echo "    Installing ${1}"
+	echo "        Copying..."
+
+	{
+		cd ${CWD}
+		mkdir -p ${3}
+		cp ${2} ${3}
+
+		echo "    Installed ${1}"
+	} || {
+		echo "    Couldn't install ${1}"
+	}
+
+	echo ""
+
 }
 
-install_plugin "Ayu Color Scheme" git://github.com/ayu-theme/ayu-vim.git
 install_plugin "Python Mode" git://github.com/python-mode/python-mode.git
+install_files "Better Python Syntax" ./syntax/python.vim ~/.vim/bundle/python-mode/syntax/
+install_files "Boxy Tomorrow" ./colors/boxy-tomorrow.vim ~/.vim/colors/
 install_plugin "NERDTree" git://github.com/scrooloose/nerdtree.git
 install_plugin "Commentary" git://github.com/tpope/vim-commentary.git
 install_plugin "Fugitive" git://github.com/tpope/vim-fugitive.git
